title: Anusha Raghunadhan
description: Full-stack developer & designer
url: "https://ah2901.github.io/Anusha.Raghunadhan.github.io/"
baseurl: ""  # Leave empty for root domain (username.github.io)

# Social links
github_username:  AH2901
linkedin_username: anusha-raghunadhan-b79bb8b7
email: anusharaghunadhan@gmail.com

# Build settings
theme: minima  # You can remove this if using custom layout
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# For SPA-like navigation
collections:
  sections:
    output: false
